"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("module-alias/register");
const Koa = require("koa");
const initKoaApp_1 = require("@util/initKoaApp");
const initKoaRouter_1 = require("@util/initKoaRouter");
const app = new Koa();
initKoaApp_1.default(app, initKoaRouter_1.default);
const port = 3000;
app.listen(port);
console.log(`server is listening in ${port}`);
