"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("module-alias/register");
const Koa = require("koa");
const ip_1 = require("@util/ip");
const index_1 = require("@socket/index");
const initKoaApp_1 = require("@util/initKoaApp");
const initKoaRouter_1 = require("@util/initKoaRouter");
const port = 3000;
const app = new Koa();
initKoaApp_1.default(app, initKoaRouter_1.default);
const server = require('http').createServer(app.callback());
const io = require('socket.io')(server);
index_1.default(io);
server.listen(port);
console.log(`http://localhost:${port}`);
console.log(`http://${ip_1.default()}:${port}`);
